import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [userAgent, setUserAgent] = useState(null)
const [userAgentData, setUserAgentData] = useState([])
const [vendor, setVendor] = useState(null)
const [appVersion, setAppVersion] = useState(null)
const [isMobile, setIsMobile] = useState(null)


  useEffect(() => {
   
    setUserAgent(navigator.userAgent)
    setUserAgentData(navigator?.userAgentData?.brands)
    setVendor(navigator.vendor)
    setAppVersion(navigator?.userAgentData?.platform)
    setIsMobile(navigator?.userAgentData?.mobile)
  }, [])

  const handleCLick = () => {
    try {
      window.open('https://business.inspigo.id', '_blank')
    } catch (error) {
      alert(error.message)
    }
  }

  const handleCLickSelft = () => {
    try {
      window.open('https://business.inspigo.id', '_self')
    } catch (error) {
      alert(error.message)
    }
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Inspigo Test Browser App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>User Agent : {userAgent}</p>
        {userAgentData && userAgentData.map((val, key) => {
          return <p key={key}>{val.brand + " Version :"+ val.version}</p>
        })}
         <p>UserVendor : {vendor}</p>
         <p>Platform : {appVersion}</p>
         <p>Mobile: {isMobile ? 'true' : 'false'}</p>

         <button type='button' onClick={handleCLick}>OPEN NEW TAB</button>
         <button type='button' onClick={handleCLickSelft}>REPLACE PAGE</button>

      </main>
    </div>
  )
}
